{
 "title": "Raw single info 2",
 "time": { "from": "2026-07-01T21:33:18.182Z", "to": "2026-07-02T03:38:42.194Z" },
 "templating": {
  "list": [
   {
    "name": "id_board_var",
    "label": "ID_board",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"sensor_data\", tag: \"id_board\")"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"sensor_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_measurements\")\n  |> filter(fn: (r) => contains(value: r[\"_field\"], set: [\"air_temp\", \"leaf_temp\", \"water_temp\"]))\n  |> filter(fn: (r) => r[\"id_board\"] == \"${id_board_var}\")\n"
    }
   ]
  },
  {
   "title": "Daily min/max on main temperature",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "query": "base_data = from(bucket: \"sensor_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_measurements\" and r[\"id_board\"] == \"${id_board_var}\")\n  |> filter(fn: (r) => contains(value: r[\"_field\"], set: [\"air_temp\", \"leaf_temp\", \"water_temp\"]))\n  |> group(columns: [\"_measurement\", \"_field\", \"id_board\"])\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\n\ndata_max = base_data\n  |> aggregateWindow(every: 1d, fn: max, createEmpty: false)\n  |> map(fn: (r) => ({ r with _field: r._field + \"_max\" }))\n\ndata_min = base_data\n  |> aggregateWindow(every: 1d, fn: min, createEmpty: false)\n  |> map(fn: (r) => ({ r with _field: r._field + \"_min\" }))\n\nunion(tables: [data_max, data_min])\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 3)\n  |> sort(columns: [\"_time\"], desc: false)\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"id_board\"])"
    }
   ]
  },
  {
   "title": "Moisture informations",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"sensor_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_measurements\")\n  |> filter(fn: (r) => r[\"id_board\"] == \"${id_board_var}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\" or r[\"_field\"] == \"soil_moisture\" or r[\"_field\"] == \"humidity_pred\")\n  "
    }
   ]
  },
  {
   "title": "Daily min/max on main temperature",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "query": "base_data = from(bucket: \"sensor_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_measurements\" and r[\"id_board\"] == \"${id_board_var}\")\n  |> filter(fn: (r) => contains(value: r[\"_field\"], set: [\"humidity\", \"soil_moisture\"]))\n  |> group(columns: [\"_measurement\", \"_field\", \"id_board\"])\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\n\ndata_max = base_data\n  |> aggregateWindow(every: 1d, fn: max, createEmpty: false)\n  |> map(fn: (r) => ({ r with _field: r._field + \"_max\" }))\n\ndata_min = base_data\n  |> aggregateWindow(every: 1d, fn: min, createEmpty: false)\n  |> map(fn: (r) => ({ r with _field: r._field + \"_min\" }))\n\nunion(tables: [data_max, data_min])\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 3)\n  |> sort(columns: [\"_time\"], desc: false)\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"id_board\"])"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "query": "from(bucket: \"sensor_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_measurements\")\n  |> filter(fn: (r) => r[\"id_board\"] == \"${id_board_var}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pressure\")"
    }
   ]
  },
  {
   "title": "Tds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "query": "from(bucket: \"sensor_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_measurements\")\n  |> filter(fn: (r) => r[\"id_board\"] == \"${id_board_var}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tds\")"
    }
   ]
  },
  {
   "title": "Solar irradiation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "query": "from(bucket: \"sensor_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"id_board\"] == \"${id_board_var}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"light_lux\")"
    }
   ]
  }
 ]
}